# Generated by Django 4.2.11 on 2024-05-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moru', '0002_remove_htels_image_url_htels_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='htels',
            name='content',
            field=models.CharField(max_length=10000000),
        ),
    ]
