# Generated by Django 4.2.11 on 2024-05-08 14:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('moru', '0003_alter_htels_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='htels',
            name='content2',
            field=models.CharField(default=django.utils.timezone.now, max_length=100000000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='htels',
            name='content3',
            field=models.CharField(default=django.utils.timezone.now, max_length=100000000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='htels',
            name='content4',
            field=models.CharField(default=django.utils.timezone.now, max_length=100000000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='htels',
            name='content5',
            field=models.CharField(default=django.utils.timezone.now, max_length=100000000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='htels',
            name='content6',
            field=models.CharField(default=django.utils.timezone.now, max_length=100000000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='htels',
            name='content',
            field=models.CharField(max_length=100000000),
        ),
    ]
