# Generated by Django 4.2.11 on 2024-05-09 04:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('moru', '0005_alter_htels_content2_alter_htels_content3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='link',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
    ]
